Workaround problem with monitoring mouse position
After moving from RHEL6 to RHEL7 and updating our PyQt, the mouse tracking
hooking code fails with the following error:

Object::connect: No such signal QObject::MouseMove(QPoint)
TypeError: connect() failed between SpyMouse.MouseMove[QPoint] and unislot()

Unfortunately I have no idea how to fix this, so for now we simply drop
this functionality.